"""Walks the trimmed MT3 venv's installed distributions and writes a
consolidated third-party notices file -- real license text/classifiers
read directly from each package's own dist-info, not a template. Python
itself, PyTorch, and mt3-infer (which carries MR-MT3's own attribution
inline -- see mt3_infer's own LICENSE, extracted separately) get their
own top-level notice files per the installer's existing per-major-
dependency convention (see native/installer/assets/Licenses/README.txt);
everything else here.

Usage (from the repo root, using any working Python -- doesn't need to
be the trimmed venv's own interpreter, just needs read access to it):
    python native/installer/scripts/gather_mt3_licenses.py \
        native/BeatShoreDesktop/python_engine/ml_env_mt3_trimmed/Lib/site-packages \
        native/installer/assets/Licenses/MT3-ModelPack-THIRD-PARTY-NOTICES.txt

Re-run this (and manually refresh Python-LICENSE.txt/PyTorch-LICENSE.txt/
mt3-infer-and-MR-MT3-LICENSE.txt from their own current source files --
see README.txt's own comment on where those come from) whenever the MT3
Model Pack's dependencies change.
"""
import importlib.metadata as im
import sys
from pathlib import Path

SITE_PACKAGES = Path(sys.argv[1])
OUT_PATH = Path(sys.argv[2])
# Already covered by their own dedicated notice files -- see
# gather standalone license files below.
SKIP = {"torch", "mt3-infer"}

sys.path.insert(0, str(SITE_PACKAGES))

lines = []
lines.append("Third-party notices for the packages bundled in BeatShore's \"MT3 Model")
lines.append("Pack\" installer component (native/BeatShoreDesktop/python_engine/), beyond")
lines.append("Python itself, PyTorch, and mt3-infer/MR-MT3 -- each of which has its own")
lines.append("dedicated notice file alongside this one (see this folder's README.txt).")
lines.append("")
lines.append("Generated by walking the actual installed distributions' own metadata")
lines.append("(importlib.metadata) in the exact venv this Model Pack was built from --")
lines.append("not a template list. Regenerate if any dependency is added, removed, or")
lines.append("upgraded.")
lines.append("")
lines.append("=" * 78)
lines.append("")

dists = sorted(im.distributions(path=[str(SITE_PACKAGES)]), key=lambda d: d.metadata["Name"].lower())
seen = set()
for dist in dists:
    name = dist.metadata["Name"]
    if name.lower() in seen:
        continue
    seen.add(name.lower())
    if name.lower() in SKIP:
        continue

    version = dist.version
    license_expr = dist.metadata.get("License-Expression", "")
    classifiers = [c for c in dist.metadata.get_all("Classifier", []) if c.startswith("License")]
    license_str = license_expr or (classifiers[0].split(" :: ")[-1] if classifiers else dist.metadata.get("License", "") or "(license not declared in metadata)")

    lines.append(f"{name} {version} -- {license_str}")

    # Real license file text, if the distribution ships one -- most modern
    # wheels do (PEP 639 / setuptools' license_files), under dist-info or
    # dist-info/licenses.
    license_text = None
    try:
        for candidate_name in ("LICENSE", "LICENSE.txt", "LICENSE.md", "LICENSE.rst", "COPYING"):
            for base in (dist._path, getattr(dist, "_path", None)):
                if base is None:
                    continue
                for sub in (base, base / "licenses"):
                    candidate = sub / candidate_name
                    if candidate.exists():
                        license_text = candidate.read_text(encoding="utf-8", errors="replace")
                        break
                if license_text:
                    break
            if license_text:
                break
    except Exception:
        license_text = None

    if license_text:
        lines.append("-" * 78)
        lines.append(license_text.strip())
    lines.append("")
    lines.append("=" * 78)
    lines.append("")

OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {OUT_PATH} -- {len(seen) - len(SKIP)} packages documented.")
